#include QMK_KEYBOARD_H

extern keymap_config_t keymap_config;

// Each layer gets a name for readability, which is then used in the keymap matrix below.
// The underscores don't mean anything - you can have a layer called STUFF or any other name.
// Layer names don't all need to be of the same length, obviously, and you can also skip them
// entirely and just use numbers.
#define _QWERTY 0
#define _MEDIA 2
#define _LOWER 3
#define _RAISE 4
#define _ADJUST 16

enum custom_keycodes {
                      QWERTY = SAFE_RANGE,
                      LOWER,
                      RAISE,
                      ADJUST,
};

#define LOWER MO(_LOWER)
#define RAISE MO(_RAISE)

enum user_macro {
  UM_HENK,
};

#define M_HENK MACROTAP(UM_HENK)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[_QWERTY] = LAYOUT( \
/* ,-----------------------------------------.                ,-----------------------------------------.
 * | EQL  |  1   |  2   |  3   |  4   |  5   |                |  6   |  7   |  8   |  9   |  0   | BSLS |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | TAB  |  Q   |  W   |  E   |  R   |  T   |                |  Y   |  U   |  I   |  O   |  P   | MINS |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | LCTL |  A   |  S   |  D   |  F   |  G   |                |  H   |  J   |  K   |  L   |LT(_ME| QUOT |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * | LSFT |  Z   |  X   |  C   |  V   |  B   | GRV  |  |LT(_ME|  N   |  M   | COMM | DOT  | SLSH | RSFT |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |LOWER | LALT |LGUI_T| SPC  | BSPC |  | TAB  |LT(_RA|LT(_RA|  UP  |M_HENK|
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
  KC_EQL,  KC_1,  KC_2,    KC_3,    KC_4,            KC_5,                                 KC_6,                KC_7,  KC_8,    KC_9,   KC_0,                KC_BSLS, \
  KC_TAB,  KC_Q,  KC_W,    KC_E,    KC_R,            KC_T,                                 KC_Y,                KC_U,  KC_I,    KC_O,   KC_P,                KC_MINS, \
  KC_LCTL, KC_A,  KC_S,    KC_D,    KC_F,            KC_G,                                 KC_H,                KC_J,  KC_K,    KC_L,   LT(_MEDIA, KC_SCLN), KC_QUOT, \
  KC_LSFT, KC_Z,  KC_X,    KC_C,    KC_V,            KC_B,   KC_GRV,  LT(_MEDIA, KC_ESC),  KC_N,                KC_M,  KC_COMM, KC_DOT, KC_SLSH,             KC_RSFT, \
                  LOWER,   KC_LALT, LGUI_T(KC_MHEN), KC_SPC, KC_BSPC, KC_TAB, LT(_RAISE,KC_ENT),  LT(_RAISE,KC_DOWN),  KC_UP,   M_HENK \
),

/* ,-----------------------------------------.                ,-----------------------------------------.
 * | TILD | EXLM |  AT  | HASH | DLR  | PERC |                | CIRC | AMPR | ASTR | LPRN | RPRN |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | TILD | EXLM |  AT  | HASH | DLR  | PERC |                | CIRC | AMPR | ASTR | LPRN | RPRN | DEL  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |  F1  |  F2  |  F3  |  F4  |  F5  |                |  F6  | LBRC | RBRC | LCBR | RCBR | PIPE |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |      |  F7  |  F8  |  F9  | F10  | F11  |      |  |      | F12  |  LT  |  GT  | LBRC | RBRC |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |      |      |      |      |      |  |      |      |      |      |      |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
[_LOWER] = LAYOUT( \
 KC_TILD, KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC,                   KC_CIRC,   KC_AMPR,   KC_ASTR, KC_LPRN, KC_RPRN, _______, \
 KC_TILD, KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC,                   KC_CIRC,   KC_AMPR,   KC_ASTR, KC_LPRN, KC_RPRN,  KC_DEL,  \
 _______, KC_F1,   KC_F2,   KC_F3,    KC_F4,    KC_F5,                     KC_F6,   KC_LBRC,   KC_RBRC, KC_LCBR, KC_RCBR, KC_PIPE, \
 _______, KC_F7,   KC_F8,   KC_F9,   KC_F10,   KC_F11, _______, _______,  KC_F12,     KC_LT,     KC_GT, KC_LBRC, KC_RBRC, _______,\
                 _______, _______,  _______,  _______, _______, _______,  _______, _______, _______, _______\
),
/* ,-----------------------------------------.                ,-----------------------------------------.
 * | GRV  |  F1  |  F2  |  F3  |  F4  |  F5  |                |  F6  |  F7  |  F8  |  F9  | F10  | F11  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | GRV  |  1   |  2   |  UP  |  4   |  5   |                |  6   |  7   |  8   |  9   |  0   | F12  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      | LEFT | DOWN | RGHT |  F5  |                |  F6  | MINS | EQL  | LBRC | RBRC | BSLS |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |      |  F7  |  F8  |  F9  | F10  | F11  | INS  |  |      | F12  | NUHS | NUBS |      |      |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |      |      |      |      | DEL  |  |      |      |      |      |      |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
[_RAISE] = LAYOUT( \
  KC_GRV,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                      KC_F6,   KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11, \
  KC_GRV,    KC_1,    KC_2,   KC_UP,    KC_4,    KC_5,                       KC_6,    KC_7,    KC_8,    KC_9,    KC_0,  KC_F12, \
 _______, _______, KC_LEFT, KC_DOWN, KC_RGHT,   KC_F5,                      KC_F6, KC_MINS,  KC_EQL, KC_LBRC, KC_RBRC, KC_BSLS, \
 _______,   KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,  KC_INS, _______,   KC_F12, KC_NUHS, KC_NUBS, _______, _______, _______, \
                   _______, _______, _______, _______,  KC_DEL, _______,  _______, _______, _______, _______\
),
/* ,-----------------------------------------.                ,-----------------------------------------.
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                |  F7  |  F8  |  F9  | F10  | F11  | F12  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      |      | MS_U |      |      |                |      |      |      |      |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      | MS_L | MS_D | MS_R |      |                | WH_L | WH_D | WH_U | WH_R |      |      |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |      |      |      |      |      |      |      |  |      |RGB_TO|RGB_MO|RGB_HU|RGB_HU|      |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |      | ACL0 | ACL1 | ACL2 |      |  | BTN1 | BTN2 |      |      |      |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */
[_MEDIA] = LAYOUT( \
   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                     KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,  KC_F12, \
 _______, _______, _______, KC_MS_U, _______, _______,                   _______, _______, _______, _______, _______, _______, \
 _______, _______, KC_MS_L, KC_MS_D, KC_MS_R, _______,                   KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, _______, _______, \
 _______, _______, _______, _______, _______, _______, _______, _______, RGB_TOG, RGB_MOD, RGB_HUD, RGB_HUI, _______, _______, \
                   _______, KC_ACL0, KC_ACL1, KC_ACL2, _______,  KC_BTN1,KC_BTN2, _______, _______, _______\
),
/* ,-----------------------------------------.                ,-----------------------------------------.
 * |  F1  |  F2  |  F3  |  F4  |  F5  |  F6  |                |  F7  |  F8  |  F9  | F10  | F11  | F12  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |RESET |      |      | MS_U |      |      |                |RGB_SA|RGB_SA|RGB_VA|RGB_VA|      | BSPC |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      | MS_L | MS_D | MS_R |      |                |AG_SWA|      |BL_TOG|BL_STE|      |      |
 * |------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 * |QWERTY|      |      |AU_ON |AU_OFF|AG_NOR|      |  |      |RGB_TO|RGB_MO|RGB_HU|RGB_HU|      |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------'
 *               |      |      |      |      |      |  |      |      |      |      |      |
 *               `----------------------------------'  `----------------------------------'
 *                                                                               generated by [keymapviz] */


[_ADJUST] =  LAYOUT( \
   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                     KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,  KC_F12, \
   RESET, _______, _______, KC_MS_U, _______, _______,                   RGB_SAD, RGB_SAI, RGB_VAD, RGB_VAI, _______, KC_BSPC, \
 _______, _______, KC_MS_L, KC_MS_D, KC_MS_R, _______,                   AG_SWAP, _______, BL_TOGG, BL_STEP, _______, _______, \
  QWERTY, _______, _______,   AU_ON,  AU_OFF, AG_NORM, _______, _______, RGB_TOG, RGB_MOD, RGB_HUD, RGB_HUI, _______, _______, \
                   _______, _______, _______, _______, _______, _______, _______, _______, _______, _______\
)
};

uint32_t layer_state_set_user(uint32_t state) {
  return update_tri_layer_state(state, _LOWER, _RAISE, _ADJUST);
}

const macro_t *action_get_macro(keyrecord_t *record, uint8_t id, uint8_t opt)
{
  switch(id) {
    case UM_HENK:
      return MACRO_TAP_HOLD_LAYER( record, MACRO(TYPE(KC_HENK), END), _RAISE );
      break;
  }
  return MACRO_NONE;
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  return true;
}
