[macros.install__ubuntu]
    prefix = ["sudo", "apt-get", "install"]
[macros.install__arch]
    prefix = ["sudo", "pacman", "-S"]
[macros.install__fedora]
    prefix = ["sudo", "dnf", "install"]
[macros.install__gentoo]
    prefix = ["sudo", "emerge"]

[tasks.default]
    links = [
        [".bashrc"],
        [".Xresources"],
        [".aliasrc"],
        [".bash_profile"],
        [".bashrc"],
        [".emacs.d"],
        [".latexmkrc"],
        [".gitignore"],
        [".gitconfig"],
        [".hgrc"],
        [".inputrc"],
        [".tmux.conf"],
        [".Xmodmap"],
        [".xmonad"],
        [".zshrc"],
        [".config/awesome"],
        [".config/fontconfig/conf.d/"]
    ]
    cmds =[
         ["mkdir", "-p","$HOME/.config/systemd/user/"],
         ["cp", "$PWD/.config/systemd/user/emacs.service","$HOME/.config/systemd/user/"]
    ]

[tasks.golang]
    envs =[
         ["GOPATH","${HOME}/.go"],
         ["mkdir","-p","${HOME}/.go"],
    ]
    cmds =[
         ["go","get","github.com/motemen/ghq"],
         ["go","get","github.com/peco/peco/cmd/peco"],
         ["go","get","github.com/dougm/goflymake"],
         ["go","get","github.com/nsf/gocode"],
         ["go","get","github.com/peco/migemogrep"],
    ]

[tasks.ghq]
    deps = ["golang"]
    cmds = [
         ["ghq","get","https://github.com/erikw/tmux-powerline.git"],
         ["ghq","get","https://github.com/majutsushi/urxvt-font-size.git"],
         ["ghq","get","https://github.com/milkbikis/powerline-shell.git"],
         ["ghq","get","https://github.com/rupa/z.git"],
         ["ghq","get","https://github.com/tmux-plugins/tpm.git"],
         ["sed","-i","s/.*THEME.*/THEME = \"my\"/","${HOME}/.ghq/github.com/milkbikis/powerline-shell/config.py"],
    ]
    links = [
          ["${HOME}/.tmux/plugins/tpm","${HOME}/.ghq/github.com/tmux-plugins/tpm"],
          ["${HOME}/.urxvt/ext/font-size","${HOME}/.ghq/github.com/majutsushi/urxvt-font-size/font-size"],
          ["${HOME}/.ghq/github.com/milkbikis/powerline-shell/themes/my.py","powerline-shell/themes/my.py"],
          ["${HOME}/.ghq/github.com/erikw/tmux-powerline/themes/default.sh","default.sh"],
    ]
[tasks.dropbox]
    cmds = [
         ["@install", "curl"],
         ["mkdir", "-p","${HOME}/bin"],
         ["curl", "https://linux.dropbox.com/packages/dropbox.py", "-o", "${HOME}/bin/dropbox"],
         ["chmod", "+x", "${HOME}/bin/dropbox"]
    ]
