;;;;色設定 http://th.nao.ac.jp/MEMBER/zenitani/elisp-j.html#color

;; (eval-when-compile
;;   (require 'color-theme))

;; (color-theme-molokai)
;;(color-theme-calm-forest)
;; (autoload 'color-theme nil t)
;; (eval-after-load "color-theme"
;;   '(progn
;;      (color-theme-initialize)
;;       (color-theme-calm-forest)

;;       ;;かっこの強調

(deftheme my/color-theme-calm-forest
  "colorrrrrrtheeeemeee")

(show-paren-mode 1)
(setq show-paren-delay 0.2
      show-paren-style 'expression)
;; (set-face-underline-p 'show-paren-match-face "red")

(custom-theme-set-faces 'my/color-theme-calm-forest
                        '(default ((t (:stipple nil :background "gray12" :foreground "green" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "unknown" :family "Ricty Discord"))))
                        '(bold ((t (:weight bold :height 0.8))))
                        '(italic ((t (:slant italic))))
                        '(bold-italic ((t (:slant italic :weight bold))))
                        '(underline ((t (:underline t))))
                        '(fixed-pitch ((t (:family "courier"))))
                        '(variable-pitch ((t (:family "helv"))))
                        '(shadow ((t (:foreground "grey70"))))
                        '(link ((t (:foreground "cyan1" :underline t))))
                        '(link-visited ((t (:foreground "violet"))))
                        '(highlight ((t (:background "darkolivegreen"))))
                        '(region ((t (:background "blue3"))))
                        '(secondary-selection ((t (:background "SkyBlue4"))))
                        '(trailing-whitespace ((t (:background "red"))))
                        '(escape-glyph ((t (:foreground "cyan"))))
                        '(nobreak-space ((t (:underline t))))
                        '(mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
                        '(mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
                        '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
                        '(mode-line-emphasis ((t (:weight bold))))
                        '(mode-line-buffer-id ((t (:weight bold))))
                        '(header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
                        '(window-divider ((t (:foreground "gray60"))))
                        '(window-divider-first-pixel ((t (:foreground "gray80"))))
                        '(window-divider-last-pixel ((t (:foreground "gray40"))))
                        '(minibuffer-prompt ((t (:foreground "cyan"))))
                        '(fringe ((t (:background "grey10"))))
                        '(border ((t (:background "black"))))
                        '(cursor ((t (:background "orange"))))
                        '(mouse ((t (:background "yellow"))))
                        '(tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
                        '(glyphless-char ((t (:height 0.6))))
                        '(error ((t (:foreground "Pink" :weight bold))))
                        '(warning ((t (:foreground "DarkOrange" :weight bold))))
                        '(success ((t (:foreground "Green1" :weight bold))))
                        '(tty-menu-enabled-face ((t (:background "blue" :foreground "yellow" :weight bold))))
                        '(tty-menu-disabled-face ((t (:background "blue" :foreground "lightgray"))))
                        '(tty-menu-selected-face ((t (:background "red"))))
                        '(show-paren-match ((t (:background "steelblue3"))))
                        '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
                        '(font-lock-comment-face ((t (:foreground "chocolate1"))))
                        '(font-lock-string-face ((t (:foreground "LightSalmon"))))
                        '(font-lock-doc-face ((t (:foreground "LightSalmon"))))
                        '(font-lock-keyword-face ((t (:foreground "Cyan"))))
                        '(font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
                        '(font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
                        '(font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
                        '(font-lock-type-face ((t (:foreground "PaleGreen"))))
                        '(font-lock-constant-face ((t (:foreground "Aquamarine"))))
                        '(font-lock-warning-face ((t (:foreground "Pink" :weight bold))))
                        '(isearch ((t (:background "palevioletred2" :foreground "brown4"))))
                        '(isearch-fail ((t (:background "red4"))))
                        '(lazy-highlight ((t (:background "paleturquoise4"))))
                        '(match ((t (:background "RoyalBlue3"))))
                        '(buffer-menu-buffer ((t (:weight bold))))
                        '(tooltip ((t (:background "lightyellow" :foreground "black"))))
                        '(haskell-debug-trace-number-face ((t (:background "#f5f5f5" :weight bold))))
                        '(haskell-debug-newline-face ((t (:background "#f0f0f0" :weight bold))))
                        '(haskell-debug-keybinding-face ((t (:weight bold))))
                        '(haskell-debug-muted-face ((t (:foreground "#999"))))
                        '(haskell-indentation-show-normal-face ((t (:underline t))))
                        '(haskell-indentation-show-hl-line-face ((t (:underline t))))
                        '(haskell-error-face ((t (:underline (:style wave :color "#dc322f")))))
                        '(haskell-warning-face ((t (:underline (:style wave :color "#b58900")))))
                        '(haskell-hole-face ((t (:underline (:style wave :color "#6c71c4")))))
                        '(popup-face ((t (:background "lightgray" :foreground "black"))))
                        '(popup-summary-face ((t (:foreground "dimgray"))))
                        '(popup-scroll-bar-foreground-face ((t (:background "black"))))
                        '(popup-scroll-bar-background-face ((t (:background "gray"))))
                        '(popup-isearch-match ((t (:background "sky blue"))))
                        '(popup-tip-face ((t (:background "khaki1" :foreground "black" :weight normal :height 0.9))))
                        '(popup-menu-mouse-face ((t (:background "blue" :foreground "white"))))
                        '(popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
                        '(ac-completion-face ((t (:foreground "darkgray" :underline t))))
                        '(ac-gtags-candidate-face ((t (:foreground "navy"))))
                        '(ac-gtags-selection-face ((t (:background "navy"))))
                        '(ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
                        '(ac-yasnippet-selection-face ((t (:background "coral3"))))
                        '(comint-highlight-input ((t (:weight bold))))
                        '(comint-highlight-prompt ((t (:foreground "cyan"))))
                        '(compilation-mode-line-fail ((t (:foreground "Red1" :weight bold))))
                        '(compilation-mode-line-exit ((t (:foreground "ForestGreen" :weight bold))))
                        '(slime-error-face ((t (:underline "red"))))
                        '(slime-warning-face ((t (:underline "coral"))))
                        '(slime-style-warning-face ((t (:underline "gold"))))
                        '(slime-note-face ((t (:underline "light goldenrod"))))
                        '(slime-highlight-face ((t (:underline nil))))
                        '(sldb-restart-number-face ((t (:weight bold))))
                        '(sldb-restartable-frame-line-face ((t (:foreground "lime green"))))
                        '(powerline-active1 ((t (:background "grey22"))))
                        '(powerline-active2 ((t (:background "grey40"))))
                        '(powerline-inactive1 ((t (:background "grey11"))))
                        '(powerline-inactive2 ((t (:background "grey20"))))
                        '(widget-documentation ((t (:foreground "lime green"))))
                        '(widget-button ((t (:weight bold))))
                        '(widget-field ((t (:background "dim gray"))))
                        '(widget-single-line-field ((t (:background "dim gray"))))
                        '(widget-inactive ((t (:foreground "light gray"))))
                        '(widget-button-pressed ((t (:foreground "red"))))
                        '(git-commit-summary-face ((t (:foreground "LightSalmon" :weight bold))))
                        '(git-commit-overlong-summary-face ((t (:foreground "Pink" :weight bold))))
                        '(git-commit-nonempty-second-line-face ((t (:foreground "Pink" :weight bold))))
                        '(git-commit-comment-face ((t (:foreground "chocolate1"))))
                        '(git-commit-pseudo-header-face ((t (:foreground "Cyan1"))))
                        '(git-commit-known-pseudo-header-face ((t (:foreground "PaleGreen"))))
                        '(git-commit-note-brace-face ((t (:foreground "Aquamarine"))))
                        '(git-commit-note-address-face ((t (:foreground "Cyan1"))))
                        '(git-commit-note-face ((t (:foreground "LightSalmon"))))
                        '(git-commit-branch-face ((t (:foreground "LightSalmon"))))
                        '(yascroll:thumb-text-area ((t (:background "slateblue"))))
                        '(yascroll:thumb-fringe ((t (:background "slateblue" :foreground "slateblue"))))
                        '(ido-first-match ((t (:weight bold))))
                        '(ido-only-match ((t (:foreground "ForestGreen"))))
                        '(ido-subdir ((t (:foreground "red1"))))
                        '(ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
                        '(mozc-preedit-selected-face ((t (:background "brown" :foreground "white"))))
                        '(mozc-preedit-face ((t (:underline t))))
                        '(mozc-cand-echo-area-focused-face ((t (:background "orange" :foreground "black"))))
                        '(mozc-cand-echo-area-candidate-face ((t (:foreground "yellow"))))
                        '(mozc-cand-echo-area-shortcut-face ((t (:foreground "grey"))))
                        '(mozc-cand-echo-area-annotation-face ((t (:foreground "grey"))))
                        '(mozc-cand-echo-area-stats-face ((t (:foreground "orange"))))
                        '(mozc-cand-overlay-focused-face ((t (:background "#ffa500" :foreground "#191970"))))
                        '(mozc-cand-overlay-odd-face ((t (:background "#27408b" :foreground "#fffacd"))))
                        '(mozc-cand-overlay-even-face ((t (:background "#27408b" :foreground "#fffacd"))))
                        '(mozc-cand-overlay-footer-face ((t (:background "#4169e1" :foreground "#fffacd"))))
                        '(helm-source-header ((t (:background "#22083397778B" :foreground "white" :weight bold :height 1.3 :family "Sans Serif"))))
                        '(helm-visible-mark ((t (:background "green1" :foreground "black"))))
                        '(helm-candidate-number ((t (:background "Yellow" :foreground "black"))))
                        '(helm-selection ((t (:background "ForestGreen"))))
                        '(helm-separator ((t (:foreground "red"))))
                        '(helm-action ((t (:underline t))))
                        '(helm-prefarg ((t (:foreground "green"))))
                        '(helm-match ((t (:foreground "gold1"))))
                        '(helm-header-line-left-margin ((t (:background "yellow" :foreground "black"))))
                        '(helm-swoop-target-line-face ((t (:background "#e3e300" :foreground "#222222"))))
                        '(helm-swoop-target-line-block-face ((t (:background "#cccc00" :foreground "#222222"))))
                        '(helm-swoop-target-word-face ((t (:background "#7700ff" :foreground "#ffffff"))))
                        '(helm-swoop-line-number-face ((t (:foreground "#999999"))))
                        '(ace-jump-face-background ((t (:foreground "gray40"))))
                        '(ace-jump-face-foreground ((t (:foreground "red" :underline nil))))
                        '(avy-lead-face-0 ((t (:background "#4f57f9" :foreground "white"))))
                        '(avy-lead-face-1 ((t (:background "gray" :foreground "white"))))
                        '(avy-lead-face-2 ((t (:background "#f86bf3" :foreground "white"))))
                        '(avy-lead-face ((t (:background "#e52b50" :foreground "white"))))
                        '(avy-background-face ((t (:foreground "gray40"))))
                        '(flycheck-error ((t (:underline (:style wave :color "Red1")))))
                        '(flycheck-warning ((t (:underline (:style wave :color "DarkOrange")))))
                        '(flycheck-info ((t (:underline (:style wave :color "ForestGreen")))))
                        '(flymake-errline ((t (:underline (:style wave :color "Red1")))))
                        '(flymake-warnline ((t (:underline (:style wave :color "DarkOrange")))))
                        '(mc/cursor-face ((t (:inverse-video t))))
                        '(calendar-today ((t (:underline t))))
                        '(diary ((t (:foreground "yellow1"))))
                        '(holiday ((t (:background "chocolate4"))))
                        '(org-hide ((t (:foreground "black"))))
                        '(org-drawer ((t (:foreground "LightSkyBlue"))))
                        '(org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal))))
                        '(org-column-title ((t (:background "grey30" :underline t :weight bold))))
                        '(org-footnote ((t (:foreground "Cyan" :underline t))))
                        '(org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
                        '(org-target ((t (:underline t))))
                        '(org-date ((t (:foreground "Cyan" :underline t))))
                        '(org-date-selected ((t (:foreground "Pink" :inverse-video t))))
                        '(org-sexp-date ((t (:foreground "Cyan"))))
                        '(org-tag ((t (:weight bold))))
                        '(org-list-dt ((t (:weight bold))))
                        '(org-todo ((t (:foreground "Pink" :weight bold))))
                        '(org-done ((t (:foreground "PaleGreen" :weight bold))))
                        '(org-agenda-done ((t (:foreground "PaleGreen"))))
                        '(org-headline-done ((t (:foreground "LightSalmon"))))
                        '(org-table ((t (:foreground "LightSkyBlue"))))
                        '(org-formula ((t (:foreground "chocolate1"))))
                        '(org-document-title ((t (:foreground "pale turquoise" :weight bold))))
                        '(org-document-info ((t (:foreground "pale turquoise"))))
                        '(org-clock-overlay ((t (:background "SkyBlue4" :foreground "white"))))
                        '(org-agenda-structure ((t (:foreground "LightSkyBlue"))))
                        '(org-agenda-date-today ((t (:slant italic :weight bold))))
                        '(org-agenda-date-weekend ((t (:weight bold))))
                        '(org-scheduled ((t (:foreground "PaleGreen"))))
                        '(org-scheduled-today ((t (:foreground "PaleGreen"))))
                        '(org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
                        '(org-scheduled-previously ((t (:foreground "chocolate1"))))
                        '(org-upcoming-deadline ((t (:foreground "chocolate1"))))
                        '(org-agenda-restriction-lock ((t (:background "#1C1C1C"))))
                        '(org-time-grid ((t (:foreground "LightGoldenrod"))))
                        '(org-latex-and-related ((t (:foreground "burlywood"))))
                        '(org-mode-line-clock-overrun ((t (:background "red"))))
                        '(sp-wrap-overlay-opening-pair ((t (:foreground "green"))))
                        '(sp-wrap-overlay-closing-pair ((t (:foreground "red"))))
                        '(sp-show-pair-match-face ((t (:background "steelblue3"))))
                        '(sp-show-pair-mismatch-face ((t (:background "purple" :foreground "white"))))
                        '(vr/match-separator-face ((t (:foreground "red" :weight bold))))
                        '(vr/match-0 ((t (:background "steelblue4"))))
                        '(vr/match-1 ((t (:background "dodgerblue4"))))
                        '(vr/group-0 ((t (:background "blue3"))))
                        '(vr/group-1 ((t (:background "chartreuse4"))))
                        '(vr/group-2 ((t (:background "sienna4"))))
                        '(ido-vertical-match-face ((t (:underline t :weight bold))))
                        '(undo-tree-visualizer-default-face ((t (:foreground "gray"))))
                        '(undo-tree-visualizer-current-face ((t (:foreground "red"))))
                        '(undo-tree-visualizer-active-branch-face ((t (:foreground "white" :weight bold))))
                        '(undo-tree-visualizer-register-face ((t (:foreground "yellow"))))
                        '(undo-tree-visualizer-unmodified-face ((t (:foreground "cyan"))))
                        '(mm-command-output ((t (:foreground "ForestGreen"))))
                        '(message-header-to ((t (:foreground "DarkOliveGreen1" :weight bold))))
                        '(message-header-cc ((t (:foreground "chartreuse1" :weight bold))))
                        '(message-header-subject ((t (:foreground "OliveDrab1"))))
                        '(message-header-newsgroups ((t (:foreground "yellow" :slant italic :weight bold))))
                        '(message-header-other ((t (:foreground "VioletRed1"))))
                        '(message-header-name ((t (:foreground "green"))))
                        '(message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
                        '(message-separator ((t (:foreground "LightSkyBlue1"))))
                        '(message-cited-text ((t (:foreground "LightPink1"))))
                        '(message-mml ((t (:foreground "MediumSpringGreen"))))
                        '(magit-section-highlight ((t (:background "grey20"))))
                        '(magit-section-heading ((t (:foreground "LightGoldenrod2" :weight bold))))
                        '(magit-section-secondary-heading ((t (:weight bold))))
                        '(magit-section-heading-selection ((t (:foreground "LightSalmon3"))))
                        '(magit-process-ok ((t (:foreground "green"))))
                        '(magit-process-ng ((t (:foreground "red"))))
                        '(diff-header ((t (:background "grey45"))))
                        '(diff-file-header ((t (:background "grey60" :weight bold))))
                        '(diff-removed ((t (:background "#553333"))))
                        '(diff-added ((t (:background "#335533"))))
                        '(diff-refine-changed ((t (:background "#aaaa22"))))
                        '(diff-refine-removed ((t (:background "#aa2222"))))
                        '(diff-refine-added ((t (:background "#22aa22"))))
                        '(smerge-mine ((t (:background "#553333"))))
                        '(smerge-other ((t (:background "#335533"))))
                        '(smerge-base ((t (:background "#888833"))))
                        '(smerge-markers ((t (:background "grey30"))))
                        '(smerge-refined-removed ((t (:background "#aa2222"))))
                        '(smerge-refined-added ((t (:background "#22aa22"))))
                        '(magit-diff-file-heading ((t (:weight bold))))
                        '(magit-diff-file-heading-selection ((t (:foreground "LightSalmon3"))))
                        '(magit-diff-hunk-heading ((t (:background "grey25" :foreground "grey70"))))
                        '(magit-diff-hunk-heading-highlight ((t (:background "grey35" :foreground "grey70"))))
                        '(magit-diff-hunk-heading-selection ((t (:foreground "LightSalmon3"))))
                        '(magit-diff-lines-heading ((t (:background "salmon4" :foreground "grey80"))))
                        '(magit-diff-added ((t (:background "#335533" :foreground "#ddffdd"))))
                        '(magit-diff-removed ((t (:background "#553333" :foreground "#ffdddd"))))
                        '(magit-diff-base ((t (:background "#555522" :foreground "#ffffcc"))))
                        '(magit-diff-context ((t (:foreground "grey70"))))
                        '(magit-diff-added-highlight ((t (:background "#336633" :foreground "#cceecc"))))
                        '(magit-diff-removed-highlight ((t (:background "#663333" :foreground "#eecccc"))))
                        '(magit-diff-base-highlight ((t (:background "#666622" :foreground "#eeeebb"))))
                        '(magit-diff-context-highlight ((t (:background "grey20" :foreground "grey70"))))
                        '(magit-diffstat-added ((t (:foreground "#448844"))))
                        '(magit-diffstat-removed ((t (:foreground "#aa4444"))))
                        '(magit-log-graph ((t (:foreground "grey80"))))
                        '(magit-log-author ((t (:foreground "tomato"))))
                        '(magit-log-date ((t (:foreground "grey80"))))
                        '(magit-reflog-commit ((t (:foreground "green"))))
                        '(magit-reflog-amend ((t (:foreground "magenta"))))
                        '(magit-reflog-merge ((t (:foreground "green"))))
                        '(magit-reflog-checkout ((t (:foreground "blue"))))
                        '(magit-reflog-reset ((t (:foreground "red"))))
                        '(magit-reflog-rebase ((t (:foreground "magenta"))))
                        '(magit-reflog-cherry-pick ((t (:foreground "green"))))
                        '(magit-reflog-remote ((t (:foreground "cyan"))))
                        '(magit-reflog-other ((t (:foreground "cyan"))))
                        '(magit-dimmed ((t (:foreground "grey50"))))
                        '(magit-hash ((t (:foreground "grey40"))))
                        '(magit-tag ((t (:foreground "LightGoldenrod2"))))
                        '(magit-branch-remote ((t (:foreground "DarkSeaGreen2"))))
                        '(magit-branch-local ((t (:foreground "LightSkyBlue1"))))
                        '(magit-branch-current ((t (:box 1))))
                        '(magit-refname ((t (:foreground "grey80"))))
                        '(magit-signature-good ((t (:foreground "green"))))
                        '(magit-signature-bad ((t (:foreground "red"))))
                        '(magit-signature-untrusted ((t (:foreground "cyan"))))
                        '(magit-cherry-unmatched ((t (:foreground "cyan"))))
                        '(magit-cherry-equivalent ((t (:foreground "magenta"))))
                        '(magit-filename ((t (:weight normal))))
                        '(magit-sequence-stop ((t (:foreground "DarkSeaGreen2"))))
                        '(magit-sequence-part ((t (:foreground "LightGoldenrod2"))))
                        '(magit-sequence-head ((t (:foreground "LightSkyBlue1"))))
                        '(magit-sequence-drop ((t (:foreground "IndianRed"))))
                        '(magit-bisect-good ((t (:foreground "DarkOliveGreen"))))
                        '(magit-bisect-skip ((t (:foreground "DarkGoldenrod"))))
                        '(magit-bisect-bad ((t (:foreground "IndianRed4"))))
                        '(magit-blame-heading ((t (:background "grey25" :foreground "black"))))
                        '(git-gutter:separator ((t (:foreground "cyan" :weight bold))))
                        '(git-gutter:modified ((t (:foreground "magenta" :weight bold :height 0.8))))
                        '(git-gutter:added ((t (:foreground "green" :weight bold :height 0.8))))
                        '(git-gutter:deleted ((t (:foreground "red" :weight bold :height 0.8))))
                        '(git-gutter:unchanged ((t (:background "yellow"))))
                        '(google-translate-translation-face ((t (:weight bold))))
                        '(google-translate-suggestion-label-face ((t (:foreground "red"))))
                        '(google-translate-suggestion-face ((t (:underline t :slant italic))))
                        '(google-translate-listen-button-face ((t (:height 0.8))))
                        '(sh-heredoc ((t (:foreground "yellow1" :weight bold))))
                        '(sh-quoted-exec ((t (:foreground "salmon"))))
                        '(emmet-preview-input ((t (:box 1))))
                        '(web-mode-error-face ((t (:background "red"))))
                        '(web-mode-symbol-face ((t (:foreground "gold"))))
                        '(web-mode-doctype-face ((t (:foreground "Grey"))))
                        '(web-mode-html-tag-face ((t (:foreground "Snow4"))))
                        '(web-mode-html-tag-bracket-face ((t (:foreground "Snow3"))))
                        '(web-mode-html-attr-name-face ((t (:foreground "Snow3"))))
                        '(web-mode-block-attr-name-face ((t (:foreground "#8fbc8f"))))
                        '(web-mode-block-attr-value-face ((t (:foreground "#5f9ea0"))))
                        '(web-mode-css-variable-face ((t (:slant italic))))
                        '(web-mode-json-key-face ((t (:foreground "plum"))))
                        '(web-mode-json-context-face ((t (:foreground "orchid3"))))
                        '(web-mode-param-name-face ((t (:foreground "Snow3"))))
                        '(web-mode-whitespace-face ((t (:background "DarkOrchid4"))))
                        '(web-mode-inlay-face ((t (:background "Black"))))
                        '(web-mode-block-face ((t (:background "Black"))))
                        '(web-mode-folded-face ((t (:underline t))))
                        '(web-mode-bold-face ((t (:weight bold))))
                        '(web-mode-italic-face ((t (:slant italic))))
                        '(web-mode-underline-face ((t (:underline t))))
                        '(web-mode-current-element-highlight-face ((t (:background "#000000"))))
                        '(web-mode-current-column-highlight-face ((t (:background "#3e3c36"))))
                        '(web-mode-comment-keyword-face ((t (:box 1 :weight bold))))
                        '(web-mode-sql-keyword-face ((t (:slant italic :weight bold))))
                        '(web-mode-html-entity-face ((t (:slant italic))))
                        '(slime-repl-input-face ((t (:weight bold))))
                        '(slime-repl-output-mouseover-face ((t (:box (:line-width 1 :color "black" :style released-button)))))
                        '(slime-repl-inputed-output-face ((t (:foreground "Red"))))
                        '(sldb-reference-face ((t (:underline t))))
                        '(helm-moccur-buffer ((t (:foreground "DarkTurquoise" :underline t))))
                        '(helm-resume-need-update ((t (:background "red"))))
                        '(helm-grep-match ((t (:foreground "gold1"))))
                        '(helm-grep-file ((t (:foreground "BlueViolet" :underline t))))
                        '(helm-grep-lineno ((t (:foreground "Darkorange1"))))
                        '(helm-grep-finish ((t (:foreground "Green"))))
                        '(helm-locate-finish ((t (:foreground "Green"))))
                        '(bookmark-menu-bookmark ((t (:weight bold))))
                        '(helm-bookmark-info ((t (:foreground "green"))))
                        '(helm-bookmark-w3m ((t (:foreground "yellow"))))
                        '(helm-bookmark-gnus ((t (:foreground "magenta"))))
                        '(helm-bookmark-man ((t (:foreground "Orange4"))))
                        '(helm-bookmark-file ((t (:foreground "Deepskyblue2"))))
                        '(helm-bookmark-addressbook ((t (:foreground "tomato"))))
                        '(helm-etags-file ((t (:foreground "Lightgoldenrod4" :underline t))))
                        '(helm-buffer-saved-out ((t (:background "black" :foreground "red"))))
                        '(helm-buffer-not-saved ((t (:foreground "Indianred2"))))
                        '(helm-buffer-size ((t (:foreground "RosyBrown"))))
                        '(helm-buffer-process ((t (:foreground "Sienna3"))))
                        '(helm-buffer-directory ((t (:background "LightGray" :foreground "DarkRed"))))
                        '(helm-ff-prefix ((t (:background "yellow" :foreground "black"))))
                        '(helm-ff-executable ((t (:foreground "green"))))
                        '(helm-ff-directory ((t (:background "LightGray" :foreground "DarkRed"))))
                        '(helm-ff-dotted-directory ((t (:background "DimGray" :foreground "black"))))
                        '(helm-ff-dotted-symlink-directory ((t (:background "DimGray" :foreground "DarkOrange"))))
                        '(helm-ff-symlink ((t (:foreground "DarkOrange"))))
                        '(helm-ff-invalid-symlink ((t (:background "red" :foreground "black"))))
                        '(helm-history-remote ((t (:foreground "Indianred1"))))
                        '(speedbar-tag-face ((t (:foreground "yellow"))))
                        '(speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
                        '(speedbar-selected-face ((t (:foreground "red" :underline t))))
                        '(speedbar-highlight-face ((t (:background "sea green"))))
                        '(speedbar-file-face ((t (:foreground "cyan"))))
                        '(speedbar-directory-face ((t (:foreground "light blue"))))
                        '(speedbar-button-face ((t (:foreground "green3"))))
                        '(show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
                        '(show-paren-match-face ((t (:background "grey30"))))
                        '(senator-read-only-face ((t (:background "#664444"))))
                        '(senator-momentary-highlight-face ((t (:background "gray30"))))
                        '(senator-intangible-face ((t (:foreground "gray75"))))
                        '(semantic-unmatched-syntax-face ((t (:underline "red"))))
                        '(semantic-dirty-token-face ((t (:background "gray10"))))
                        '(jde-java-font-lock-underline-face ((t (:underline t))))
                        '(jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
                        '(jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
                        '(jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
                        '(jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
                        '(jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
                        '(jde-java-font-lock-italic-face ((t (:slant italic))))
                        '(jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
                        '(jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
                        '(jde-java-font-lock-bold-face ((t (:weight bold))))
                        '(jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
                        '(jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
                        '(jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
                        '(jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
                        '(jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
                        '(info-xref ((t (:foreground "cyan" :weight bold))))
                        '(info-node ((t (:foreground "white" :slant italic :weight bold))))
                        '(info-menu-header ((t (:weight bold :family "helv"))))
                        '(info-menu-5 ((t (:foreground "red1"))))
                        '(info-header-xref ((t (:foreground "cyan" :weight bold))))
                        '(info-header-node ((t (:foreground "white" :slant italic :weight bold))))
                        '(font-latex-warning-face ((t (:foreground "Red" :weight bold))))
                        '(font-latex-string-face ((t (:foreground "RosyBrown"))))
                        '(font-latex-sedate-face ((t (:foreground "LightGray"))))
                        '(font-latex-math-face ((t (:foreground "burlywood"))))
                        '(font-latex-italic-face ((t (:foreground "OliveDrab" :slant italic))))
                        '(font-latex-bold-face ((t (:foreground "OliveDrab" :weight bold))))
                        '(extra-whitespace-face ((t (:background "pale green"))))
                        '(eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
                        '(custom-variable-tag-face ((t (:foreground "light blue" :weight bold :height 1.2 :family "helv"))))
                        '(custom-variable-button-face ((t (:underline t :weight bold))))
                        '(custom-state-face ((t (:foreground "lime green"))))
                        '(custom-set-face ((t (:background "white" :foreground "blue"))))
                        '(custom-saved-face ((t (:underline t))))
                        '(custom-rogue-face ((t (:background "black" :foreground "pink"))))
                        '(custom-modified-face ((t (:background "blue" :foreground "white"))))
                        '(custom-invalid-face ((t (:background "red" :foreground "yellow"))))
                        '(custom-group-tag-face-1 ((t (:foreground "pink" :weight bold :height 1.2 :family "helv"))))
                        '(custom-group-tag-face ((t (:foreground "light blue" :weight bold :height 1.2))))
                        '(custom-face-tag-face ((t (:weight bold :height 1.2 :family "helv"))))
                        '(custom-comment-tag-face ((t (:foreground "gray80"))))
                        '(custom-comment-face ((t (:background "dim gray"))))
                        '(custom-changed-face ((t (:background "blue" :foreground "white"))))
                        '(custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
                        '(custom-button-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
                        '(cparen-normal-paren-face ((t (:foreground "grey50"))))
                        '(cparen-conditional-clause-face ((t (:foreground "RoyalBlue"))))
                        '(cparen-binding-list-face ((t (:foreground "ForestGreen" :weight bold))))
                        '(cparen-binding-face ((t (:foreground "ForestGreen"))))
                        '(cparen-around-vector-face ((t (:foreground "chocolate"))))
                        '(cparen-around-syntax-rules-face ((t (:foreground "Magenta"))))
                        '(cparen-around-set!-face ((t (:foreground "OrangeRed"))))
                        '(cparen-around-quote-face ((t (:foreground "SaddleBrown"))))
                        '(cparen-around-letdo-face ((t (:foreground "LightSeaGreen" :weight bold))))
                        '(cparen-around-lambda-face ((t (:foreground "LightSeaGreen"))))
                        '(cparen-around-define-face ((t (:foreground "Blue" :weight bold))))
                        '(cparen-around-conditional-face ((t (:foreground "RoyalBlue" :weight bold))))
                        '(cparen-around-begin-face ((t (:foreground "maroon"))))
                        '(cparen-around-andor-face ((t (:foreground "maroon" :weight bold))))
                        '(Info-title-4-face ((t (:weight bold :family "helv"))))
                        '(Info-title-3-face ((t (:weight bold :height 1.2 :family "helv"))))
                        '(Info-title-2-face ((t (:weight bold :height 1.44 :family "helv"))))
                        '(Info-title-1-face ((t (:weight bold :height 1.728 :family "helv")))))
(require 'color)

(defun xah-syntax-color-hsl ()
  "Syntax color CSS's HSL color spec ⁖ 「hsl(0,90%,41%)」 in current buffer.
URL `http://ergoemacs.org/emacs/emacs_CSS_colors.html'
Version 2015-06-11"
  (interactive)
  (font-lock-add-keywords
   nil
   '(("hsl( *\\([0-9]\\{1,3\\}\\) *, *\\([0-9]\\{1,3\\}\\)% *, *\\([0-9]\\{1,3\\}\\)% *)"
      (0 (put-text-property
          (+ (match-beginning 0) 3)
          (match-end 0)
          'face
          (list
           :background
           (concat
            "#"
            (mapconcat
             'identity
             (mapcar
              (lambda (x) (format "%02x" (round (* x 255))))
              (color-hsl-to-rgb
               (/ (string-to-number (match-string-no-properties 1)) 360.0)
               (/ (string-to-number (match-string-no-properties 2)) 100.0)
               (/ (string-to-number (match-string-no-properties 3)) 100.0)))
             "" )) ;  "#00aa00"
           ))))))
  (font-lock-fontify-buffer))

(defun xah-syntax-color-hex ()
  "Syntax color text of the form 「#ff1100」 in current buffer.
URL `http://ergoemacs.org/emacs/emacs_CSS_colors.html'
Version 2015-06-11"
  (interactive)
  (font-lock-add-keywords
   nil
   '(("#[abcdefABCDEF[:digit:]]\\{6\\}"
      (0 (put-text-property
          (match-beginning 0)
          (match-end 0)
          'face (list :background (match-string-no-properties 0)))))))
  (font-lock-fontify-buffer))
