;; ;;cua-mode
;; (cua-mode t)
;; (setq cua-enable-cua-keys nil)
;; (setq cua-auto-tabify-rectangles nil)
;; (transient-mark-mode 1)
;; (setq cua-keep-region-after-copy nil)
;; (setq cua-enable-keys nil)
;; ;; (add-hook 'cua-mode-hook
;; ;;         '(lambda ()
;; ;;            (global-unset-key "\)")
;; ;;            (global-unset-key  "}" )
;; ;;            (global-unset-key "\]")
;; ;;            (global-unset-key  ">" )
;; ;;            (global-unset-key  "\"")
;; ;;            (global-unset-key  "'" )))
