;; (require 'smartrep)
;; (smartrep-define-key
;;     global-map "M-g" '(("M-n" . 'flymake-goto-next-error)
;;                        ("M-p" . 'flymake-goto-prev-error)))
;; (define-key python-mode-map (kbd "C-c f") 'flymake-goto-next-error)
(defun python-mode-hooks ()
  (highlight-indentation-mode)
  (highlight-indentation-current-column-mode)
  (flymake-python-pyflakes-load)
  (auto-complete-mode)
  (company-mode -1)
  (jedi:setup)
  ;; (whitespace-mode)
  (setq jedi:setup-keys t
		jedi:complete-on-dot t)
  (set-face-background 'highlight-indentation-face "gray4")
  (set-face-background 'highlight-indentation-current-column-face "gray20")
  (add-to-list 'company-backends 'company-jedi)
  (setq-default tab-width 4 indent-tabs-mode t))

(with-eval-after-load 'python
  (bind-keys :map python-mode-map
			 ("M-<left>"  . python-indent-shift-left)
			 ("C-c h"     . python-indent-shift-left)
			 ("M-<right>" . python-indent-shift-right)
			 ("C-c l"     . python-indent-shift-right))
  (add-hook 'python-mode-hook 'python-mode-hooks))
;; (require 'flymake-python-pyflakes)
;; (require 'highlight-indentation)
;; (require 'whitespace)
