;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		anything-filelist+
		beginning-of-indented-line
		c-electric-delete-forward
		c-electric-paren
		c-electric-semi&comma
		c-electric-star
		cua-clear-rectangle-mark
		flymake-goto-next-error
		kill-buffer
		mozc-handle-event
		my-insert-bracket
		my-insert-paren
		switch-to-buffer
		))

(setq mc/cmds-to-run-once
      '(
		cua-delete-region
		eval-buffer
		toggle-input-method
		))
