;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-indented-line
        cua-delete-region
        go-mode-insert-and-indent
        org-delete-char
        org-forward-sentence
        org-self-insert-command
        sp--cua-replace-region
        sp--self-insert-command
        toggle-input-method
        ))

(setq mc/cmds-to-run-once
      '(
        org-end-of-line
        ))
